config/routes.rb
Rails.application.routes.draw do

  root 'text_book_collection#index'
  resources :text_book_collections, only: [:index] do
    resources :vocabulary_drills, only: [:index]
    resources :kanji_drills, only: [:index]
  end

end

app/models/kanji_drill_item.rb
class KanjiDrillItem < ActiveRecord::Base
  belongs_to :text_book_collection

  def self.random_word_for_collection(collection_id)
    temp = self.where(text_book_collection_id: collection_id)
    size = temp.size
    temp.offset(rand(size)).first
  end

  def self.possible_translations
    self.offset(rand(self.count)).limit(4).pluck(:translated_reading)
  end
end

app/models/text_book_collection.rb
class TextBookCollection < ActiveRecord::Base
  has_many :kanji_drill_items
  has_many :vocabulary_drill_items

end

app/models/vocabulary_drill_item.rb
class VocabularyDrillItem < ActiveRecord::Base
  belongs_to :text_book_collection

  def self.random_word_for_collection(collection_id)
    temp = self.where(text_book_collection_id: collection_id)
    size = temp.size
    temp.offset(rand(size)).first
  end

  def self.possible_translations
    self.offset(rand(self.count)).limit(4).pluck(:translated_reading)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/kanji_drills_controller.rb
class KanjiDrillsController < ApplicationController
  def index
    @word = KanjiDrillItem.random_word_for_collection(params['text_book_collection_id'])
    @readings = KanjiDrillItem.possible_translations
    @readings << @word.translated_reading
    @readings.uniq!
    @readings.shuffle!
  end
end

app/controllers/text_book_collection_controller.rb
class TextBookCollectionController < ApplicationController
  def index
    @collections = TextBookCollection.all
  end
end

app/controllers/vocabulary_drills_controller.rb
class VocabularyDrillsController < ApplicationController
  def index
    @word = VocabularyDrillItem.random_word_for_collection(params['text_book_collection_id'])
    @readings = VocabularyDrillItem.possible_translations
    @readings << @word.translated_reading
    @readings.uniq!
    @readings.shuffle!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kanji_drills_helper.rb
module KanjiDrillsHelper
end

app/helpers/text_book_collection_helper.rb
module TextBookCollectionHelper
end

app/helpers/vocabulary_drills_helper.rb
module VocabularyDrillsHelper
end

app/views/kanji_drills/index.html.erb
<h3>Выберите правильный перевод:</h3>
<h4><%=@word.native_reading%></h4>



<%= content_tag "div", id: "form", data: {answer: @word.translated_reading } do %>
  <form id='quiz_form'>
  <%@readings.each do |reading|%>
    <p><input type="radio" name='drill' value= '<%=reading%>' >  <%=reading%></p>
  <%end%>
  </form>
  <button id='submit' class='btn btn-primary'>Check</button>
<% end %>

<div id='warning' class="panel panel-danger half-width">
  <div class="panel-heading">Не угадали</div>
  <div class="panel-body">Попробуйте еще раз</div>
</div>

<script>
$('#warning').hide();
$('#submit').click(function(){
  var correct_answer = $('#form').data('answer');
  var checked_answer = $( "input:checked" ).val();
  if(correct_answer == checked_answer){
    location.reload();
  } else {
    $('#warning').fadeToggle( "slow", "linear" );
    setTimeout(function(){
      $('#warning').fadeToggle( "slow", "linear" );
    },1000)
  };
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JfTestSystem</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class='container'>
  <div class='row header'>
    <div class="col-md-6">
      <h1><a href='<%=root_path%>'>Marugoto kanji drill</a></h1>
      <h3>Пока доступен только наш желтый учебник №3 - в остальных мусор</h3>
    </div>
    <div class="col-md-6">
      <h1><a href='<%=root_path%>'>Japan foundation</a></h1>
    </div>
  </div>
      <%= yield %>
</div>
</body>
</html>

app/views/text_book_collection/index.html.erb
<%@collections.each do |collection|%>
  <div class='row'>
    <div class="col-md-12">
      <h4><%=collection.title%></h4>
      <image src=<%=collection.picture_url%> />
      <ul>
        <li><a href=<%=text_book_collection_vocabulary_drills_path(collection.id)%>>Тренируем словарь</a></li>
       <li><a href=<%=text_book_collection_kanji_drills_path(collection.id)%>>Тренируем кандзи</a></li>
      </ul>
    </div>
  </div>
<%end%>

app/views/vocabulary_drills/index.html.erb
<h3>Выберите правильный перевод:</h3>
<h4><%=@word.native_reading%></h4>

<%= content_tag "div", id: "form", data: {answer: @word.translated_reading } do %>
  <form id='quiz_form'>
  <%@readings.each do |reading|%>
    <p><input type="radio" name='drill' value=  '<%=reading%>' >  <%=reading%></p>
  <%end%>
  </form>
  <button id='submit' class='btn btn-primary'>Check</button>
<% end %>

<div id='warning' class="panel panel-danger half-width">
  <div class="panel-heading">Не угадали</div>
  <div class="panel-body">Попробуйте еще раз</div>
</div>

<script>
$('#warning').hide();
$('#submit').click(function(){
  var correct_answer = $('#form').data('answer');
  var checked_answer = $( "input:checked" ).val();
  if(correct_answer == checked_answer){
    location.reload();
  } else {
    $('#warning').fadeToggle( "slow", "linear" );
    setTimeout(function(){
      $('#warning').fadeToggle( "slow", "linear" );
    },1000)
  };
});
</script>